[config]
schemaVersion = "0.0.1"

[package]
namespace = "MoSadie"
name = "TemplatePlugin"
versionNumber = "1.0.0"
description = "A Template Plugin, this description should be changed!"
websiteUrl = "https://github.com/MoSadie/Slipstream-Template-Plugin"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack= "5.4.2100"
MoSadie-MoCore= "1.0.0"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./TemplatePlugin/bin/Release/netstandard2.1/com.mosadie.templateplugin.dll"
target = "BepInEx/plugins/MoSadie-TemplatePlugin/com.mosadie.templateplugin.dll"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[publish]
repository = "https://thunderstore.io"
communities = [ "slipstream-rogue-space", ]
[publish.categories]
slipstream-rogue-space = [ "mods" ]


